// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_venda_api.Data.Context;

#nullable disable

namespace project_venda_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211205911_Titulo-dbcontext")]
    partial class Titulodbcontext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project_venda_api.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TipoCliente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("project_venda_api.Models.Influenciador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Influenciadores");
                });

            modelBuilder.Entity("project_venda_api.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("project_venda_api.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("project_venda_api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("project_venda_api.Models.Titulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aceite")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CNPJCPF")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CaracTitulo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Carteira")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodTransmissao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CodigoCedente")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CodigoMora")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Convenio")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DataDesconto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDocumento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMoraJuros")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMulta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataProtesto")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiasDeProtesto")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EspecieMod")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Instrucao1")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Instrucao2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LayoutBol")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LocalPagamento")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("MultaValorFixo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NossoNumero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Parcela")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("PercentualMulta")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RespEmis")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("SeuNumero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoCarteira")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDesconto")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TipoDesconto2")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TipoDiasProtesto")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoImpressao")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TotalParcelas")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<decimal?>("ValorAbatimento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDocumento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorIOF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorMoraJuros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorMulta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorOutrasDespesas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Titulos");
                });

            modelBuilder.Entity("project_venda_api.Models.PedidoItem", b =>
                {
                    b.HasOne("project_venda_api.Models.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("project_venda_api.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
